[[units]]
tag = "NewbieMercenary"
name = "傭兵-若人"
kind = "unit"
race = "human"
image = "NewbieMercenary.png"
class_build = "NewbieMercenary"
class_tag = "LineInfantryM14"
skills = ["gunMercenary", "sword"]
level = 1
level_max = 100
vision_radius = 6
price = 1000
cost = 200
hp = 300
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 30
move = 500

[[units]]
tag = "NewbieKouhei"
name = "工兵"
kind = "unit"
race = "human"
image = "pi.png"
class_build = "NewbieKouhei"
class_tag = "LineInfantryM14"
skills = ["gunMercenary", "sword"]
level = 1
level_max = 100
vision_radius = 6
price = 1000
cost = 200
hp = 300
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 30
move = 500

[[units]]
tag = "LineInfantryM14"
name = "M14 Infantry Rifle"
kind = "unit"
race = "human"
image = "chipGene001.png"
class_build = "Kouhei"
class_tag = "LineInfantryM14"
skills = ["gunLaphroaig", "healKiai", "grenadier_throw"]
level = 1
level_max = 100
vision_radius = 6
price = 1000
cost = 10
hp = 300
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 30
move = 500

[[units]]
tag = "Home"
name = "参謀本部"
kind = "building"
race = "human"
image = "home1.png"
class_build = "home"
class_tag = "LineInfantryM14"
skills = ["gunLaphroaig", "healKiai"]
level = 1
level_max = 100
vision_radius = 6
price = 1000
cost = 10
hp = 0
building_hp = 200
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 5
move = 500

[[units]]
tag = "sniperP99"
name = "P99 Sniper Rifle"
kind = "unit"
race = "human"
image = "chipGene008.png"
class_build = ""
class_tag = "sniperP99"
skills = ["gunSnipe"]
level = 1
level_max = 100
vision_radius = 0
price = 1000
cost = 10
hp = 300
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 60
move = 500
maintain_range = 650

[[units]]
tag = "SkirmisherEni"
name = "Eni Skirmisher"
kind = "unit"
race = "human"
image = "chipGene001.png"
class_build = ""
class_tag = "SkirmisherEni"
skills = ["gunSkirmisher", "bayonetAttack"]
level = 1
level_max = 100
vision_radius = 6
price = 1000
cost = 10
hp = 400
mp = 100
attack = 25
defense = 25
magic = 30
magic_defense = 20
speed = 60
move = 500
