[[units]]
tag = "Home"
name = "参謀本部"
kind = "building"
race = "human"
image = "home1.png"
class_build = "home"
class_tag = "LineInfantryM14"
skills = ["gunLaphroaig", "healKiai"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 1000
food_cost = 0
hp = 0
building_hp = 200
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 5
move = 475
maintain_range = 0
visual_scale = 2.8
visual_offset = [0, 20]
shadow_offset = [0, 4]
placement_anchor = "bottom_center"
render_size_mode = "gameplay"
gameplay_size_mul = 2.2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "NewbieMercenary"
name = "傭兵-若人"
kind = "unit"
race = "human"
image = "NewbieMercenary.gif"
class_build = "NewbieMercenary"
class_tag = "LineInfantryM14"
skills = ["gunMercenary", "sword"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 150
trust_cost = 1000
food_cost = 0
hp = 300
building_hp = 0
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 30
move = 500
maintain_range = 0
visual_scale = 2
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "NewbieKouhei"
name = "工兵"
kind = "unit"
race = "human"
image = "pi.gif"
class_build = "NewbieKouhei"
class_tag = "LineInfantryM14"
skills = ["gunMercenary", "sword"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 150
trust_cost = 1000
food_cost = 0
hp = 300
building_hp = 0
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 30
move = 175
maintain_range = 0
visual_scale = 3
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "ironWall"
name = "鉄条網"
kind = "building"
race = "human"
image = "ironWall.png"
class_build = "Kouhei"
class_tag = "LineInfantryM14"
skills = ["gunLaphroaig", "healKiai"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 1000
food_cost = 0
hp = 9999
building_hp = 9999
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 0
move = 0
maintain_range = 0
visual_scale = 1
visual_offset = [0, -16]
shadow_offset = [0, -57]
placement_anchor = "bottom_center"
render_size_mode = "art"
gameplay_size_mul = 2.2
art_width_ref = "cell"
art_width_value = 0.9999999999999997
art_width_value_line_horizontal = 0.9999999999999997
art_width_value_line_diag_up_right = 0.6999999999999996
art_width_value_line_diag_up_left = 0.5999999999999996
art_keep_aspect = true
line_icon_horizontal_offset = [0, -15]
line_icon_diag_up_right_offset = [16, -4]
line_icon_diag_up_left_offset = [-16, -8]

[[units]]
tag = "NewbieMercenary_copy"
name = "軽装歩兵"
kind = "unit"
race = "human"
image = "RightInf.gif"
class_build = "NewbieMercenary"
class_tag = "LineInfantryM14"
skills = ["gunMercenary", "sword"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 150
trust_cost = 1000
food_cost = 0
hp = 300
building_hp = 0
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 30
move = 500
maintain_range = 0
visual_scale = 2
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "LineInfantryM14Tumejo"
name = "ラミィ小規模歩兵詰所"
kind = "building"
race = "human"
image = "bu-keiso.png"
class_build = "keisouHohei"
class_tag = "LineInfantryM14"
skills = []
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 100
food_cost = 0
hp = 0
building_hp = 200
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 5
move = 0
maintain_range = 0
visual_scale = 2
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "bottom_center"
render_size_mode = "gameplay"
gameplay_size_mul = 2.2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "keisouTumejo"
name = "軽装歩兵詰所"
kind = "building"
race = "human"
image = "bu-keiso.png"
class_build = "keisouHohei"
class_tag = "LineInfantryM14"
skills = []
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 100
food_cost = 0
hp = 0
building_hp = 200
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 5
move = 0
maintain_range = 0
visual_scale = 1.6
visual_offset = [0, -6]
shadow_offset = [0, -32]
placement_anchor = "bottom_center"
render_size_mode = "gameplay"
gameplay_size_mul = 2.2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "keisouTumejo_copy"
name = "機動部隊集合地点"
kind = "building"
race = "human"
image = "bu-keiso.png"
class_build = "keisouHohei"
class_tag = "LineInfantryM14"
skills = []
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 100
food_cost = 0
hp = 0
building_hp = 200
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 5
move = 0
maintain_range = 0
visual_scale = 1.6
visual_offset = [0, -6]
shadow_offset = [0, -32]
placement_anchor = "bottom_center"
render_size_mode = "gameplay"
gameplay_size_mul = 2.2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "LineInfantryM14"
name = "M14ライフル銃兵"
kind = "unit"
race = "human"
image = "chipGene001.png"
class_build = "Kouhei"
class_tag = "LineInfantryM14"
skills = ["gunLaphroaig", "healKiai", "grenadier_throw"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 1000
food_cost = 0
hp = 300
building_hp = 0
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 30
move = 500
maintain_range = 0
visual_scale = 1
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "BrenGunCarrier"
name = "ブレンガン・キャリアー"
kind = "unit"
race = "human"
image = "unicarri.png"
class_build = "BrenGunCarrier"
class_tag = "LineInfantryM14"
skills = ["gunLaphroaig", "healKiai"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 1000
food_cost = 0
hp = 9999
building_hp = 0
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 500
move = 500
maintain_range = 0
visual_scale = 1
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "LineInfantryM14_copy"
name = "チャクラム兵"
kind = "unit"
race = "human"
image = "Chakram.png"
class_build = "Kouhei"
class_tag = "LineInfantryM14"
skills = ["gunLaphroaig", "healKiai", "grenadier_throw"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 1000
food_cost = 0
hp = 300
building_hp = 0
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 30
move = 500
maintain_range = 0
visual_scale = 1
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "Kettenkrad"
name = "ケッテンクラート"
kind = "unit"
race = "human"
image = "kettenkrad.png"
class_build = "BrenGunCarrier"
class_tag = "LineInfantryM14"
skills = ["gunLaphroaig", "healKiai"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 1000
food_cost = 0
hp = 300
building_hp = 0
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 5
move = 500
maintain_range = 0
visual_scale = 1
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "sniperP99"
name = "P99 Sniper Rifle"
kind = "unit"
race = "human"
image = "chipGene008.png"
class_build = ""
class_tag = "sniperP99"
skills = ["gunSnipe"]
level = 1
level_max = 100
vision_radius = 0
gold_cost = 10
trust_cost = 1000
food_cost = 0
hp = 300
building_hp = 0
mp = 100
attack = 55
defense = 25
magic = 30
magic_defense = 20
speed = 60
move = 500
maintain_range = 650
visual_scale = 1
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

[[units]]
tag = "SkirmisherEni"
name = "Eni Skirmisher"
kind = "unit"
race = "human"
image = "chipGene001.png"
class_build = ""
class_tag = "SkirmisherEni"
skills = ["gunSkirmisher", "bayonetAttack"]
level = 1
level_max = 100
vision_radius = 6
gold_cost = 10
trust_cost = 1000
food_cost = 0
hp = 400
building_hp = 0
mp = 100
attack = 25
defense = 25
magic = 30
magic_defense = 20
speed = 60
move = 500
maintain_range = 0
visual_scale = 1
visual_offset = [0, 0]
shadow_offset = [0, 0]
placement_anchor = "center"
render_size_mode = "gameplay"
gameplay_size_mul = 2
art_width_ref = "cell"
art_width_value = 1
art_width_value_line_horizontal = 1
art_width_value_line_diag_up_right = 1
art_width_value_line_diag_up_left = 1
art_keep_aspect = true
line_icon_horizontal_offset = [0, 0]
line_icon_diag_up_right_offset = [0, 0]
line_icon_diag_up_left_offset = [0, 0]

