[[rooms]]
id = "bonus_room_1"
page_count = 3

[[rooms]]
id = "bonus_room_2"
page_count = 3

[[rooms]]
id = "bonus_room_3"
page_count = 3

[[rooms]]
id = "bonus_room_4"
page_count = 3

[[rooms]]
id = "bonus_room_5"
page_count = 3
