#include "BalanceEditScene.h"

BalanceEditScene::HelpText BalanceEditScene::getHoveredHelpText() const
{
	if (getTopButtonRect(0).mouseOver())
	{
		return{ U"Back", U"Return to the title scene. Unsaved local edits in this editor are discarded." };
	}
	if (getTopButtonRect(1).mouseOver())
	{
		return{ U"Apply Overrides", U"Reload config from disk and re-apply both manual _override and _editor_override files." };
	}
	if (getTopButtonRect(2).mouseOver())
	{
		return{ U"Save", U"Write the current editor values into editor-only override TOML files." };
	}
	if (getTopButtonRect(3).mouseOver())
	{
		return{ U"Clear Editor", U"Delete only _editor_override files generated by this editor and reload the base/manual overrides." };
	}
	if (getTopButtonRect(4).mouseOver())
	{
		return{ U"Clear All", U"Delete both manual _override files and editor _editor_override files for core and unit balance." };
	}
	if (getTabButtonRect(Tab::Core).mouseOver())
	{
		return{ U"Core Tab", U"Edit economy, spawn, and enemy AI pacing values from battle_core data." };
	}
	if (getTabButtonRect(Tab::Units).mouseOver())
	{
		return{ U"Units Tab", U"Edit unit stats and player production slot values from battle_units data." };
	}

	if (m_tab == Tab::Units)
	{
		for (size_t index = 0; index < m_editConfig.unitDefinitions.size(); ++index)
		{
			const auto& unit = m_editConfig.unitDefinitions[index];
			if (getUnitButtonRect(static_cast<int32>(index)).mouseOver())
			{
				return{
					toUnitArchetypeDisplayString(unit.archetype),
					unit.description.isEmpty() ? U"Select this unit to edit its combat and queue balance values." : unit.description
				};
			}
		}
	}

	const auto rowHelp = (m_tab == Tab::Core)
		? getHoveredCoreRowHelp()
		: getHoveredUnitRowHelp();
	if (rowHelp)
	{
		return *rowHelp;
	}

	return{
		U"Balance Editor",
		U"Hover a control or stat row to see what it affects. Save writes editor-only overrides, while Apply Overrides reloads files from disk."
	};
}

Optional<BalanceEditScene::HelpText> BalanceEditScene::getHoveredCoreRowHelp() const
{
	for (int32 row = 0; row < 10; ++row)
	{
		if (!getEditorRowRect(row).mouseOver())
		{
			continue;
		}

		switch (row)
		{
		case 0:
			return HelpText{ U"Player Gold", U"Player starting gold. Higher values let the player open with more buildings or units." };
		case 1:
			return HelpText{ U"Enemy Gold", U"Enemy starting gold. Raising this makes the enemy establish faster in early battle time." };
		case 2:
			return HelpText{ U"Income Interval", U"Time between automatic gold income ticks. Lower is faster economy for both sides." };
		case 3:
			return HelpText{ U"Player Income", U"Gold gained by the player on each income tick." };
		case 4:
			return HelpText{ U"Enemy Income", U"Gold gained by the enemy on each income tick." };
		case 5:
			return HelpText{ U"Spawn Interval", U"Enemy spawn cadence. Lower values create more constant pressure." };
		case 6:
			return HelpText{ U"Advanced Spawn Rate", U"Chance that enemy spawns the advanced archetype instead of the basic one." };
		case 7:
			return HelpText{ U"Spawn Random Y", U"Vertical random spread applied to enemy spawn positions." };
		case 8:
			return HelpText{ U"Assault Threshold", U"Enemy AI waits until this many units are ready before switching to stronger assault behavior." };
		case 9:
			return HelpText{ U"Staging Min Units", U"Minimum units gathered before staging assault commits. Larger values delay attacks but make pushes denser." };
		default:
			break;
		}
	}

	return none;
}

Optional<BalanceEditScene::HelpText> BalanceEditScene::getHoveredUnitRowHelp() const
{
	const bool hasProductionSlot = (getSelectedProductionSlot() != nullptr);
	const int32 rowCount = hasProductionSlot ? 9 : 7;
	for (int32 row = 0; row < rowCount; ++row)
	{
		if (!getEditorRowRect(row).mouseOver())
		{
			continue;
		}

		if (row == 0)
		{
			return HelpText{ U"HP", U"Unit durability. Higher HP increases time alive and usually lowers control stress by making losses less sharp." };
		}
		if (row == 1)
		{
			return HelpText{ U"Attack", U"Damage dealt per attack event. Raising this improves burst and focus fire efficiency." };
		}
		if (row == 2)
		{
			return HelpText{ U"Unit Cost", U"Default cost taken from the unit definition. Used unless a production slot cost override exists." };
		}

		if (hasProductionSlot)
		{
			switch (row)
			{
			case 3:
				return HelpText{ U"Queue Cost", U"Actual player production command cost. If this is set above zero, it overrides the unit's default cost in the command menu and queue." };
			case 4:
				return HelpText{ U"Batch Count", U"How many units are produced from one queue action. Bigger values increase burst production and reduce input count." };
			case 5:
				return HelpText{ U"Production Time", U"Time required to finish one queue item for this unit." };
			case 6:
				return HelpText{ U"Move Speed", U"Travel speed. Higher values improve reinforcement speed and chase potential." };
			case 7:
				return HelpText{ U"Attack Range", U"Distance at which the unit can attack. Higher values improve safety and first-hit control." };
			case 8:
				return HelpText{ U"Attack Cooldown", U"Delay between attacks. Lower values mean faster repeated attacks." };
			default:
				return HelpText{ U"Aggro Range", U"Detection radius for engaging targets. Higher values make units react earlier." };
			}
		}

		switch (row)
		{
		case 3:
			return HelpText{ U"Production Time", U"Time required to finish one queue item for this unit." };
		case 4:
			return HelpText{ U"Move Speed", U"Travel speed. Higher values improve reinforcement speed and chase potential." };
		case 5:
			return HelpText{ U"Attack Range", U"Distance at which the unit can attack. Higher values improve safety and first-hit control." };
		case 6:
			return HelpText{ U"Attack Cooldown", U"Delay between attacks. Lower values mean faster repeated attacks." };
		default:
			return HelpText{ U"Aggro Range", U"Detection radius for engaging targets. Higher values make units react earlier." };
		}
	}

	if ((getSelectedProductionSlot() == nullptr) && getEditorRowRect(7).mouseOver())
	{
		return HelpText{ U"Aggro Range", U"Detection radius for engaging targets. Higher values make units react earlier." };
	}

	return none;
}
