schema_version = 1
id = "default"
display_name = "Default Skirmish"
map = "015_BattleMapCellImage/map_editor_map.toml"
resource_nodes = "070_Scenario/InfoResource/Map001.ResourceNodes.toml"
ai_profile = ""
