[layout]

grid = 8

info_x = 1296

info_bottom = 352

command_x = 1296

command_y = 736

resource_x = 1296

resource_y = 112

param_editor_x = 672

param_editor_y = 112

building_editor_x = 672

building_editor_y = 112

resource_node_editor_x = 528

resource_node_editor_y = 64

decal_editor_x = 720

decal_editor_y = 64

perlin_panel_x = 816

perlin_panel_y = 64

z_order_panel_x = 776

z_order_panel_y = 64

info_top_anchor = true

command_top_anchor = false

resource_top_anchor = true

param_editor_top_anchor = false

building_editor_top_anchor = false

