[[resource_nodes]]

resource_kind = "gold"

position = [680, 570]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "trust"

position = [440, 930]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "food"

position = [1760, 930]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "gold"

position = [200, 1170]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "gold"

position = [800, 1170]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "gold"

position = [1760, 1290]

amount = 700

income_per_sec = 5


