[[resource_nodes]]

resource_kind = "trust"

position = [4280, 450]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "trust"

position = [1280, 570]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "food"

position = [2600, 570]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "trust"

position = [560, 1410]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "gold"

position = [2240, 2130]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "food"

position = [4040, 2130]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "food"

position = [2600, 2370]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "food"

position = [680, 2490]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "trust"

position = [2360, 2490]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "food"

position = [2000, 4170]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "trust"

position = [560, 4290]

amount = 700

income_per_sec = 5


[[resource_nodes]]

resource_kind = "trust"

position = [2960, 4290]

amount = 700

income_per_sec = 5


